"""add file metadata columns

Revision ID: 059392a25378
Revises: cfac037a5972
Create Date: 2026-01-14 13:46:41.088735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059392a25378'
down_revision = 'cfac037a5972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('content_type')
        batch_op.drop_column('storage_path')

    # ### end Alembic commands ###
